[config]
default_type = "scheme-tonal-spot"

[config.wallpaper]
command = "swww"

[templates.niri]
input_path = 'templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'
